version: '3.8'
services:
  web:
    build: .
    image: ibkr-rest-api
    container_name: ibkr
    environment:
      IBKR_ACCOUNT_ID: "DU4178446"
      IBKR_PAPER_USER: "keche4295"
    ports:
      - "5055:5055"
      - "5056:5056"
